### ISSUE TITLE
Converter a apostila

### ISSUE THREAD

**Issue by maicoqb** [PHProgramando/phprogramando#1]
Utilizar o [Pandoc](http://pandoc.org/) para converter a [apostila](https://drive.google.com/file/d/0Bw6VR4q5k46CMjhIcG54V1dzWWM/view?usp=sharing) para .md

**Comment by maicoqb** [comment]
Ao converter o .odt temos que:

- [x] Separar o arquivo em capítulos
e colocar os capítulos em pastas separadas. Bem como o [Pro Git](https://github.com/progit/progit/tree/master/en/).
- [x] Extrair as imagens 
e separá-las em uma pasta de imagens dentro dos capítulos

**Comment by vitormattos** [comment]
Manda o comando aí utilizado para fazer a conversão ou o passo a passo. Fiquei curioso.

**Comment by maicoqb** [comment]
#### 1. Converter para `docx` 
O `pandoc` só extrai imagens de arquivos `.docx` ou ` .epub` então tive que converter o `.odt` para `.docx`.

#### 2. Converter para `md` 
Criar a pasta para as imagens: `img`
Pra converter é só utilizar o comando:
``` pandoc -f docx -t markdown -s -S --extract-media=img -o curso_php_basico.md Curso_PHP_Basico.docx ```

#### 3. Organizando a saída 
O arquivo de saída vai ser um `md` com todo o texto do `docx`. Então tive que separar ele por capítulos. Após essa separação, vasculhei as imagens, algumas não foram importadas. E por fim fiz inclusão das que falaram.
